language: cpp python

python: '2.7'

compiler:  
  - gcc

before_script:  
  - files=`find . -name \*.h ! -name \*gtest.h -print -o -name \*.cpp -print -o -name \*.c -print | sed -e ':a;N;$!ba;s/\n/ /g'`
  - python ./3rdparty/utils/cpplint.py --filter=-legal/copyright,-runtime/threadsafe_fn,-build/include,-readability/utf8 $files
  - mkdir build
  - cd build
  - cmake ..

script:   
  - make  
